### ISSUE TITLE
NER evaluation documentation 

### ISSUE THREAD

**Issue by tsamardzic** [rankastankovic/It-Sr-NER#1]
The texts under https://github.com/rankastankovic/It-Sr-NER/tree/main/eval/sr are in Italian. How can Serbian annotation be retrieved from these files?

**Comment by rankastankovic** [comment]
Serbian annotation dataset with 1000 manualy corrected sentences for 7 NER classes is added in TSV (WebAnno format), conll 2002, NIF, XML formats.

**Comment by tsamardzic** [comment]
Thanks for your response. Could you please provide a link here? 
For some reason, I find it hard to find this TSV.

**Comment by rankastankovic** [comment]
https://github.com/rankastankovic/It-Sr-NER/tree/main/eval/sr

**Comment by rankastankovic** [comment]
https://github.com/rankastankovic/It-Sr-NER/blob/main/eval/sr/NER_sr.tsv

**Comment by tsamardzic** [comment]
Great, thanks a lot!  I was looking elsewhere thinking that these files had been somewhere, just that I didn't see them. 

While skimming quickly through the file, I spotted a couple of errors (probably easy to fix):

7-14	934-942	Eleninom	_	_	_	
7-15	943-951	napretku	_	_	_	


8-15	1028-1036	Saratore	*	LOC	_	
8-16	1037-1038	.	_	_	_

**Comment by rankastankovic** [comment]
Tnx, we will change.
